name: Build multi-arch Docker Image

on:
  release:
    types: [ published ]
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - run: go version

      - name: modVerify
        run: go mod verify

      - name: modTidy
        run: go mod tidy

      - name: ensure compilation
        env:
          GOOS: linux
        run: go build

      - name: Test
        run: go test -v ./...

      - name: Login to Docker Hub
        # Only if we need to push an image
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Setup for buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker info
        run: docker info
      - name: Buildx inspect
        run: docker buildx inspect

      # In case linux/s390x fails with tls issues:
      # see https://github.com/testcontainers/moby-ryuk/pull/26
      # and https://github.com/testcontainers/moby-ryuk/pull/40
      - name: Cross Build for Linux and Windows
        env:
          RYUK_VERSION: ${{ github.event.release.tag_name || github.sha }}
          IS_RELEASE: ${{ (github.event_name == 'release' && github.event.action == 'published' && 'yes') || 'no' }}
        # Use a 'temp' tag, that won't be pushed, for non-release builds
        run: |
          ./build-multiarch.sh testcontainers/ryuk:${RYUK_VERSION} ${IS_RELEASE}
