name: Build multi-arch Docker Image

on:
  release:
    types: [ published ]
  push:
    branches: [ main ]
  pull_request:

env:
  RYUK_VERSION: ${{ github.event.release.tag_name || github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - run: go version

      - name: modVerify
        run: go mod verify

      - name: modTidy
        run: go mod tidy

      - name: ensure compilation
        env:
          GOOS: linux
        run: go build

      - name: Test
        run: go test -v ./...

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Setup for buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker info
        run: docker info
      - name: Buildx inspect
        run: docker buildx inspect

      # In case linux/s390x fails with tls issues:
      # see https://github.com/testcontainers/moby-ryuk/pull/26
      # and https://github.com/testcontainers/moby-ryuk/pull/40
      - name: Cross Build for Linux and Windows
        run: |
          ./build-multiarch.sh testcontainers/ryuk:${RYUK_VERSION} 'yes'

  run-images:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Pull Ryuk
        run: docker pull testcontainers/ryuk:${RYUK_VERSION}

      - name: Run Ryuk on Linux
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: docker run -v /var/run/docker.sock:/var/run/docker.sock testcontainers/ryuk:${RYUK_VERSION}

      - name: Run Ryuk on Windows
        if: ${{ matrix.os == 'windows-2022' }}
        run: docker run -v //./pipe/docker_engine://./pipe/docker_engine testcontainers/ryuk:${RYUK_VERSION}
        continue-on-error: true
