name: Build multi-arch Docker Image

on:
  release:
    types: [published]
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      # Only if we need to push an image
      if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Setup for buildx
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    # Debugging information
    - name: Docker info
      run: docker info
    - name: Buildx inspect
      run: docker buildx inspect

    # Build and (optionally) push the image
    - name: Build image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
# s390x disabled, trying to debug strange tls cert issues
#        platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le
        # Only push if we are publishing a release
        push: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        # Use a 'temp' tag, that won't be pushed, for non-release builds
        tags: testcontainers/ryuk:${{ github.event.release.tag_name || 'temp' }}

  build-windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      # Only if we need to push an image
      if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Debugging information
    - name: Docker info
      run: docker info

    - name: Build image
      # Use a 'temp' tag, that won't be pushed, for non-release builds
      run: |
        docker build -f windows/Dockerfile -t testcontainers/ryuk:${{ github.event.release.tag_name || 'temp' }}-windows.amd64 .
    - name: Push image
      # Only push if we are publishing a release
      if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
      run: |
        docker push testcontainers/ryuk:${{ github.event.release.tag_name }}-windows.amd64

  publish-multi-arch:
    # Only if we need to push an image
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    needs:
      - build-linux
      - build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Setup for buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.6.1

      # Debugging information
      - name: Docker info
        run: docker info
      - name: Buildx inspect
        run: docker buildx inspect

      - name: Docker Manifest
        run: |
          docker buildx imagetools create -t testcontainers/ryuk:${{ github.event.release.tag_name }} \
            testcontainers/ryuk:${{ github.event.release.tag_name }}-linux \
            testcontainers/ryuk:${{ github.event.release.tag_name }}-windows.amd64
...
