name: Release multi-arch Docker Image

on:
  release:
    types: [ published ]

env:
  IMAGE_REPOSITORY: testcontainers/ryuk

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go version

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: go-mod verify
        run: go mod verify

      - name: go-mod tidy
        run: go mod tidy

      - name: go-build
        env:
          GOOS: linux
        run: go build

      - name: go-test
        run: go test -v ./...

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker info
        run: docker info
      - name: Buildx inspect
        run: docker buildx inspect

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: linux/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v6
          push: true
          tags: ${{ env.IMAGE_REPOSITORY }}:${{ github.event.release.tag_name }}-linux

  release-windows:
    strategy:
      matrix:
        os-version:
          - ltsc2019
          - ltsc2022
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go version

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: go-mod verify
        run: go mod verify

      - name: go-mod tidy
        run: go mod tidy

      - name: go-build
        env:
          GOOS: windows
        run: go build

      # TODO enable tests on Windows
      # Currently doesn't succeed, see https://github.com/testcontainers/testcontainers-go/issues/948
      #- name: go-test
      #  run: go test -v ./...

      - name: Docker info
        run: docker info

      - name: Build image
        run: |
          docker build -f windows/Dockerfile --build-arg BASE_IMAGE=mcr.microsoft.com/windows/nanoserver:${{ matrix.os-version }} -t ${{ env.IMAGE_REPOSITORY }}:${{ github.event.release.tag_name }}-windows.amd64.${{ matrix.os-version }} .

      - name: Push image
        run: |
          docker push ${{ env.IMAGE_REPOSITORY }}:${{ github.event.release.tag_name }}-windows.amd64.${{ matrix.os-version }}

  release:
    needs:
      - release-linux
      - release-windows
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker info
        run: docker info
      - name: Buildx inspect
        run: docker buildx inspect

      - name: Get os version for nanoserver:ltsc2019
        run: >-
          full_version=$(docker manifest inspect mcr.microsoft.com/windows/nanoserver:ltsc2019 | jq -r '.manifests[]|.platform|."os.version"'| sed 's@.*:@@') || true;
          echo "OS_VERSION_ltsc2019=${full_version}" >> $GITHUB_ENV;

      - name: Get os version for nanoserver:ltsc2022
        run: >-
          full_version=$(docker manifest inspect mcr.microsoft.com/windows/nanoserver:ltsc2022 | jq -r '.manifests[]|.platform|."os.version"'| sed 's@.*:@@') || true;
          echo "OS_VERSION_ltsc2022=${full_version}" >> $GITHUB_ENV;

      - name: Docker Manifest
        run: >-
          target_image=${{ env.IMAGE_REPOSITORY }}:${{ github.event.release.tag_name }};
          linux_manifest=$(docker manifest inspect ${target_image}-linux);
          linux_digests=$(docker manifest inspect ${target_image}-linux | jq -r '.manifests[].digest');
          manifest_list=${linux_digests//sha256:/${target_image%%:*}@sha256:};
          manifest_list+=" ${target_image}-windows.amd64.ltsc2019";
          manifest_list+=" ${target_image}-windows.amd64.ltsc2022";
          docker manifest create ${target_image} ${manifest_list};
          docker manifest annotate \
              --os-version ${OS_VERSION_ltsc2019} \
              --os windows \
              --arch amd64 \
              ${target_image} "${target_image}-windows.amd64.ltsc2019";
          docker manifest annotate \
              --os-version ${OS_VERSION_ltsc2022} \
              --os windows \
              --arch amd64 \
              ${target_image} "${target_image}-windows.amd64.ltsc2022";
          docker manifest push ${target_image};
